name: Build webapp image

on:
  push:
    branches:
      - main
  workflow_dispatch: # Trigger workflow manually

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download data files
        run: |
          for f in {leg_stats,stop_stats,stop_line}.parquet; do
              curl -o $f https://kaaveland-bus-eta-data.hel1.your-objectstorage.com/$f
          done

      - name: Build Docker image
        run: |
          version=${{ github.sha }}
          docker buildx create --use
          docker buildx build . \
            --platform "linux/amd64,linux/arm64" \
            -t ghcr.io/${{ github.repository }}:latest \
            -t ghcr.io/${{ github.repository }}:$version \
            --push
