name: Push frontend to CDN

on:
  push:
    paths:
      - frontend/**
      - mise.toml
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://kollektivkart-ts-poc.b-cdn.net

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: jdx/mise-action@v2
      - name: Install dependencies
        working-directory: frontend
        run: npm install
      - name: Build frontend bundle
        working-directory: frontend
        run: npm run build
      - name: Upload
        run: thumper sync --verbose frontend/dist ${{ secrets.BUNNYCDN_ZONE }}
        env:
          THUMPER_KEY: ${{ secrets.THUMPER_KEY }}
      - name: Clear cache
        run: thumper purge-zone ${{ secrets.BUNNYCDN_PULL_ZONE }}
        env:
          THUMPER_API_KEY:
            ${{ secrets.THUMPER_API_KEY }}